### ISSUE TITLE
Excellent work! 

### ISSUE THREAD

**Issue by lucasjinreal** [Aneureka/push-to-kindle#2]
Hi, I found many tools push books to kindle all complicated and annoying with ads, except this one is clean and very intuitive. 

Wanna ask, If this project plan to make a feature which pushing books automatically to our target account? That would be much more helpful when we cyclicity checking kindle for new books.

**Comment by Aneureka** [comment]
Thanks for appreciating this work, but I am wondering what "automatically" means? I'm unable to get your interest. 🤒
BTW, I plan to add a feature to make user choose to share the books they push to their devices, by clicking the checkbox, and others can view the shared book lists. But this may exists some legal issues...

**Comment by lucasjinreal** [comment]
I think it's pushing new materials such as book, pdfs scrap from internet.

That concerns user's private things.
