### ISSUE TITLE
能否不需要Mailgun也能用？

### ISSUE THREAD

**Issue by liangzhdp** [Aneureka/push-to-kindle#5]
注册Mailgun，到电话认证后，就被暂停使用了，需要回答一大堆问题，英文水，搞不掂。
有不需要mailgun就能用的方法吗？（隐私原因不包括直接用现成的）

**Comment by Aneureka** [comment]
可以的，Mailgun 只是一个邮件服务，你可以用自己的邮箱，设定 smtp 相关的配置就可以了，只是一般来讲普通邮箱不支持一天发太多封邮件，或者你也可以使用其他的邮件服务（比如 Sendgrid ）

**Comment by liangzhdp** [comment]
是修改app/service/mail.py这行吗？
    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.login('postmaster@%s' % xxxxxx@gmail.com, passwdxxxxxx)
不行啊，上传时提示遇到错误。

另外，下面这个错误没影响吧？
./run.sh.example
./run.sh.example:行3: venv/bin/activate: 没有那个文件或目录

**Comment by Aneureka** [comment]
当然有影响，你需要创建自己的virtualenv环境呀... 另外建议看看 python smtp 邮件发送的部分 理解一下
